name: femivio_project

description: "Femivio"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^5.0.2   # ✅ Added for internet connectivity check
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0  # ✅ For animated illustrations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Bike.png

# fonts:
#   - family: Poppins
#     fonts:
#       - asset: assets/fonts/Poppins-Regular.ttf
#       - asset: assets/fonts/Poppins-SemiBold.ttf
#         weight: 600
#       - asset: assets/fonts/Poppins-Bold.ttf
#         weight: 700
